### ISSUE TITLE
Researching doesn't work

### ISSUE THREAD

**Issue by cheesymyst** [DaveRainbowin/whattheburger#10]
**Describe the bug**
- The bug is researching doesn't work.

**To Reproduce**
1. Go to https://daverainbowin.github.io/whattheburger/.
2. Click on research tab/menu.
3. Scroll down to nowhere.
4. Fix the researching buttons and things.

**Expected behavior**
- Should have researching work.

**Screenshots**
- Screenshot not needed

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser: [Chrome]
 - Version [80.0.3987.87]

**Smartphone (please complete the following information):**
- Using PC

**Additional context**
- None

**Comment by DaveRainbowin** [comment]
Issue #9 is too similar too this. Closed.
