### ISSUE TITLE
Dark Theme should be fixed

### ISSUE THREAD

**Issue by cheesymyst** [DaveRainbowin/whattheburger#9]
**Describe the bug**
- The bug is that dark theme in the options doesn't work.

**To Reproduce**
1. Go to https://daverainbowin.github.io/whattheburger/
2. Click on options tab/menu
3. Scroll down to nowhere
4. Fix the broken dark theme button

**Expected behavior**
- Should change the game to dark theme.

**Screenshots**
- Screenshot not needed

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser: [Chrome]
 - Version [80.0.3987.87]

**Smartphone (please complete the following information):**
- Using PC

**Additional context**
- None

**Comment by DaveRainbowin** [comment]
This issue only exists in the downloadable version.

**Comment by DaveRainbowin** [comment]
I'll close this for now since it seems to work for everything but the downloadable version.

**Comment by DaveRainbowin** [comment]
so i had to break it for the autosave part so uh um.... rip

**Comment by cheesymyst** [comment]
Kthx

**Comment by DaveRainbowin** [comment]
dark theme is now default
